Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -86,8 +86,8 @@ jobs:
           repository: ${{ github.repository }}
           ref: ${{ inputs.branch }}
           
-      - name: Force Failure
-        run: exit 1
+      # - name: Force Failure
+      #   run: exit 1
 
       - name: Set up JDK 17
         id: jdk-setup
@@ -97,58 +97,58 @@ jobs:
           distribution: ${{ inputs.jdk_distribution }}
           cache: maven
     
-      - name: Set up Maven
-        id: maven-setup
-        uses: s4u/setup-maven-action@v1.13.0
-        with:
-          maven-version: '3.9.6'
+  #     - name: Set up Maven
+  #       id: maven-setup
+  #       uses: s4u/setup-maven-action@v1.13.0
+  #       with:
+  #         maven-version: '3.9.6'
         
-      # - name: Build with Maven
-      #   run: mvn ${{ inputs.mvn_options }} ${{inputs.mvn_actions}} --file ${{ inputs.mvn_file }}
+  #     # - name: Build with Maven
+  #     #   run: mvn ${{ inputs.mvn_options }} ${{inputs.mvn_actions}} --file ${{ inputs.mvn_file }}
       
-      - name: Post a message in a channel
-        if: always()
-        uses: slackapi/slack-github-action@v2.0.0
-        with:
-          webhook: ${{ env.SLACK_WEBHOOK_URL }}
-          webhook-type: incoming-webhook
-          payload: |
-            attachments:
-              - color: "${{ job.status == 'success' && 'good' || 'danger' }}"
-                fields:
-                  - title: "Repository"
-                    value: "${{ github.repository }}"
-                    short: true
-                  - title: "Branch"
-                    value: "${{ github.ref_name }}"
-                    short: true
-                  - title: "Pipeline"
-                    value: "${{ github.workflow }}"
-                    short: true
-                  - title: "JDK Setup"
-                    value: "${{ steps.jdk-setup.outcome == 'success' && '✅ SUCCESS' || '❌ FAILED' }}"
-                    short: false
-                  - title: "Maven setup"
-                    value: "${{ steps.maven-setup.outcome == 'success' && '✅ SUCCESS' || '❌ FAILED' }}"
-                    short: false
-                  - title: "JFrog Artifact Upload"
-                    value: "${{ steps.retrieve_secret.outcome == 'success' && '✅ SUCCESS' || '❌ FAILED' }}"
-                    short: false
+  #     - name: Post a message in a channel
+  #       if: always()
+  #       uses: slackapi/slack-github-action@v2.0.0
+  #       with:
+  #         webhook: ${{ env.SLACK_WEBHOOK_URL }}
+  #         webhook-type: incoming-webhook
+  #         payload: |
+  #           attachments:
+  #             - color: "${{ job.status == 'success' && 'good' || 'danger' }}"
+  #               fields:
+  #                 - title: "Repository"
+  #                   value: "${{ github.repository }}"
+  #                   short: true
+  #                 - title: "Branch"
+  #                   value: "${{ github.ref_name }}"
+  #                   short: true
+  #                 - title: "Pipeline"
+  #                   value: "${{ github.workflow }}"
+  #                   short: true
+  #                 - title: "JDK Setup"
+  #                   value: "${{ steps.jdk-setup.outcome == 'success' && '✅ SUCCESS' || '❌ FAILED' }}"
+  #                   short: false
+  #                 - title: "Maven setup"
+  #                   value: "${{ steps.maven-setup.outcome == 'success' && '✅ SUCCESS' || '❌ FAILED' }}"
+  #                   short: false
+  #                 - title: "JFrog Artifact Upload"
+  #                   value: "${{ steps.retrieve_secret.outcome == 'success' && '✅ SUCCESS' || '❌ FAILED' }}"
+  #                   short: false
                     
-  retry-entire-workflow:
-      if: failure() && inputs.retry_count < 3  # Use inputs.retry_count instead of env.RETRY_COUNT
-      needs: [build]
-      runs-on: ubuntu-latest
-      steps:
-      - name: Increase Retry Count
-        run: echo "NEXT_RETRY=$(( ${{ inputs.retry_count }} + 1 ))" >> $GITHUB_ENV
+  # retry-entire-workflow:
+  #     if: failure() && inputs.retry_count < 3  # Use inputs.retry_count instead of env.RETRY_COUNT
+  #     needs: [build]
+  #     runs-on: ubuntu-latest
+  #     steps:
+  #     - name: Increase Retry Count
+  #       run: echo "NEXT_RETRY=$(( ${{ inputs.retry_count }} + 1 ))" >> $GITHUB_ENV
 
-      - name: Retry Entire Workflow
-        uses: benc-uk/workflow-dispatch@v1
-        with:
-          workflow: "main.yml"
-          token: ${{ secrets.PAT_FOR_GITHUB }}
-          inputs: '{ "retry_count": "${{ env.NEXT_RETRY }}" }'
+  #     - name: Retry Entire Workflow
+  #       uses: benc-uk/workflow-dispatch@v1
+  #       with:
+  #         workflow: "main.yml"
+  #         token: ${{ secrets.PAT_FOR_GITHUB }}
+  #         inputs: '{ "retry_count": "${{ env.NEXT_RETRY }}" }'
       # - name: Log in to Docker hub
       #   uses: docker/login-action@v3
       #   with:
